# adapted from https://github.com/azuwis/actions/tree/7236424fa0fdc8d82df7cd4bff831a9d2338ce9e/nix
name: Install Nix and setup cache
inputs:
  nix_conf:
    description: Extra nix.conf config
    default: |
      accept-flake-config = true
      build-dir = /nix/var
      experimental-features = pipe-operator
      keep-derivations = true
      keep-outputs = true
  clean:
    description: Clean up disk space
    default: false
  btrfs:
    description: Use BTRFS to setup RAID0
    default: false
  attic_token:
    description: token to access attic cache

runs:
  using: composite
  steps:
    - shell: bash
      env:
        CLEAN: ${{ inputs.clean }}
        BTRFS: ${{ inputs.btrfs }}
      run: exec ${{ github.action_path }}/prepare.sh

    - uses: DeterminateSystems/nix-installer-action@v15
      with:
        source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
        extra-conf: ${{ inputs.nix_conf }}

    - name: Install and login to attic cache
      shell: bash
      run: |
        nix profile install "nixpkgs#attic-client"
        attic login oizys https://attic.dayl.in "${{ inputs.attic_token}}"
