name: Build NixOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        host: ["othalan", "algiz", "mannaz"]
    runs-on: ubuntu-latest
    steps:
      # free up some space
      - run: sudo rm -rf /opt&

      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25 # v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: daylin
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build
        run: |
          nix build \
            '.#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel' \
            --accept-flake-config
      - name: Push
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        run: cachix push daylin ./result
