name: Build NixOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  HOSTS: "algiz othalan mannaz"

jobs:
  build:
    # strategy:
      # matrix:
        # hosts: "algiz othalan mannaz"
        # try to use the cache here along the way
      # fail-fast: true
      # max-parallel: 1
    runs-on: ubuntu-latest
    steps:
      # free up some space
      - run: sudo rm -rf /opt&

      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25 # v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: daylin
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build
        run: |
          for host in "$HOSTS"
          do
            cachix watch-exec daylin -- \
            nix build \
              ".#nixosConfigurations.$host.config.system.build.toplevel" \
              --accept-flake-config \
              --print-build-logs
          done
      - name: Push
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        run: cachix push daylin ./result
