name: Build NixOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  HOSTS: "algiz othalan mannaz"
  TERM: xterm # so styx will just get on with it

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # free up some space
      - run: sudo rm -rf /opt&

      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25 # v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: daylin
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build
        run: |
          for host in ${HOSTS[@]}
          do
            nix run ".#styx" --accept-flake-config -- cache --host:$host --flake:.
          done
      # - name: Push
      #   env:
      #     CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
      #   run: cachix push daylin ./result
