name: Build NixOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      - matrix: ["othalan", "mannaz", "algiz"]
    steps:
      # free up some space
      - run: sudo rm -rf /opt&

      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25 # v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: daylin
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # - name: Build all flake outputs
      #   run: |
      #     cachix watch-exec daylin -- \
      #     nix build github:srid/devour-flake \
      #     -L --no-link --print-out-paths \
      #     --override-input flake .
      - name: Build
        run: |
          for host in ${HOSTS[@]}
          do
            nix run . --accept-flake-config -- cache --host $host --flake .
          done
