name: Build NixOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        host: ["othalan", "mannaz", "algiz"]
    steps:
      # free up some space
      - run: sudo rm -rf /opt&

      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v14
        with:
          name: daylin
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: |
          nix flake lock --update-input inputs
          nix run . --accept-flake-config -- cache --host "${{ matrix.host }}" --flake .
