name: Run Nix Flake Checks

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      lockFile:
        description: 'flake.lock file'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.host }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/clean-disk
        with:
          purge-packages: false

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - uses: cachix/cachix-action@v15
        with:
          name: daylin
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: write lock file
        if: "${{ inputs.lockFile != '' }}"
        run: |
          echo '${{ inputs.lockFile }}' > flake.lock
          git diff

      - name: Build
        run: |
          cachix watch-exec daylin -- nix build --accept-flake-config '.#checks.x86_64-linux.makePackages'
