name: Build NixOS

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.host }}
  cancel-in-progress: true

jobs:
  # checks:
  #   uses: ./.github/workflows/checks.yml
  #   secrets: inherit
  
  build:
    # needs: checks
    strategy:
      max-parallel: 1
      matrix:
        host:
          - othalan
          # - mannaz
          # - algiz
    uses: ./.github/workflows/build.yml
    with:
      host: "${{ matrix.host }}"
    secrets: inherit
